### ISSUE TITLE
PHPMD messages appear/disappear when I save the file

### ISSUE THREAD

**Issue by mignz** [sandhje/vscode-phpmd#30] opened 2018-01-07 16:16 UTC
I am having this weird issue with phpmd warnings on the code showing when I save the file and if I make a change on the file (not correcting the issue) and save it, the warning disappears. If I make another change the warnings appear again and so on... It's not just one warning, it's all PHPMD warnings on the file. I can literally add an unused variable to the code and then add a space, save, add another space, save... and the warning keeps showing/hiding.

Do you know about this? How can I debug?

**Comment by sandhje** [comment] 2018-01-10 20:58
Hi Miguel,

Thank you for taking the time to report this issue. You can debug by enabling the verbose logs for phpmd in the vscode settings. You can then find the logs in the output panel. If this does not help you to find the cause of the issue, please post the logs here with detailed steps for me to reproduce the issue so I can investigate and provide a fix.

**Comment by mignz** [comment] 2018-01-17 21:53
Hi. The output doesn't show any message.

I've made a small recording showing what's happening using a small portion of code. Note that I press CMD+S to save the file every time I type a dot in the comment to demonstrate.

![jan-17-2018 20-51-03](https://user-images.githubusercontent.com/358114/35069027-73fee540-fbc8-11e7-8e05-6831391518fc.gif)

**Comment by sandhje** [comment] 2018-01-18 20:29
Thanks for the recording and the logs, I'll take a closer look at it ASAP, probably this weekend. On first glance it might have something to do with the warning, but to be sure I have to reproduce it. I'll get back to you with what I find.

**Comment by sandhje** [comment] 2018-01-29 22:15
I was able to reproduce the issue by triggering notices on the phpmd output. Added an ltrim to the xml result to strip off any notices, warnings or other "stuff" php might add to the PHPMD output. See PR https://github.com/sandhje/vscode-phpmd/pull/33. Fix will be in the next release.

**Closed by sandhje** 2018-01-29 22:15 UTC
Labels: bug
